plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1
filters:
  tag:creator: ansible

hostnames:
  - ip-address

keyed_groups:
  - key: tags.os
    prefix: os

compose:
  ansible_user: "'Administrator' if tags.os == 'windows' else 'ec2-user'"
  ansible_connection: "'winrm' if tags.os == 'windows' else 'ssh'"
  ansible_port: "5986 if tags.os == 'windows' else 22"
  ansible_password: ''
  ansible_winrm_transport: "'ntlm' if tags.os == 'windows' else ''"
  ansible_winrm_server_cert_validation: "'ignore' if tags.os == 'windows' else ''"
  ansible_ssh_private_key_file: "'secrets/ssh-key.pem' if tags.os != 'windows' else ''"
