- name: Fetch Windows instance info and passwords
  hosts: localhost
  gather_facts: false
  
  vars:
    private_key_path: "{{ playbook_dir }}/../secrets/ssh-key.pem"

  tasks:
    - name: Collect Windows hosts info (instance_id and IP)
      set_fact:
        windows_hosts_info: "{{ windows_hosts_info | default([]) + [ {'name': item, 'instance_id': hostvars[item].instance_id, 'ip': hostvars[item].ansible_host | default(item) } ] }}"
      loop: "{{ groups['os_windows'] }}"
      run_once: true

    - name: Debug collected Windows hosts info
      debug:
        var: windows_hosts_info
      run_once: true

    - name: Get Windows password for each Windows host
      vars:
        command: >-
          aws ec2 get-password-data
          --instance-id {{ item.instance_id }}
          --priv-launch-key {{ private_key_path }}
          --query PasswordData
          --output text
      shell: "{{ command }}"
      register: password_result
      loop: "{{ windows_hosts_info }}"
      loop_control:
        label: "{{ item.name }}"
      run_once: true

    - name: Ensure host_vars directory exists for each Windows host
      file:
        path: "{{ playbook_dir }}/../host_vars/{{ item.name }}"
        state: directory
        mode: '0755'
      loop: "{{ windows_hosts_info }}"

    - name: Combine Windows host info and password results
      set_fact:
        windows_passwords: "{{ windows_passwords | default([]) + [ {'name': item.0.name, 'password': item.1.stdout} ] }}"
      loop: "{{ windows_hosts_info | zip(password_result.results) | list }}"
      run_once: true

    - name: Save Windows password to host_vars file
      copy:
        dest: "{{ playbook_dir }}/../host_vars/{{ item.name }}/windows_password.yml"
        content: |
          ansible_password: "{{ item.password }}"
      loop: "{{ windows_passwords }}"
