---
- name: Launch EC2 Instances
  hosts: localhost
  gather_facts: false

  vars:
    key_name: "First EC2 Instance - 19/06/2025"
    region: ap-south-1

  tasks:
    - name: Launch EC2 instance with Linux Image
      amazon.aws.ec2_instance:
        name: linux-inst-ansible
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        instance_type: t2.micro
        image_id: ami-0a1235697f4afa8a4
        wait: true
        count: 1
        security_group: sg-02d290fb435aa47d1
        tags:
          Creator: Ansible
      register: ec2_linux

    - name: Launch EC2 instance with Windows Image
      amazon.aws.ec2_instance:
        name: win-inst-ansible
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        instance_type: t3.micro
        image_id: ami-05b85154f69f6bcb3
        wait: true
        count: 1
        security_group: sg-02d290fb435aa47d1
        tags:
          Creator: Ansible
      register: ec2_win

    - name: List Public IPv4 Addesses of linux instance
      ansible.builtin.debug:
        msg: "{{ ec2_linux.instances[0].instance_id }}:{{ ec2_linux.instances[0].public_ip_address }}"

    - name: List Public IPv4 Addesses of windows instance
      ansible.builtin.debug:
        msg: "{{ ec2_win.instances[0].instance_id }}:{{ ec2_win.instances[0].public_ip_address }}"
...
