---
- name: Launch EC2 Instances
  hosts: localhost
  gather_facts: false

  vars:
    key_name: "ansible-key-pair"
    region: ap-south-1
    security_group: sg-02d290fb435aa47d1
    ec2_instances:
      - name: linux-inst-ansible
        instance_type: t2.micro
        image_id: ami-0a1235697f4afa8a4
        count: 1
        os: linux
        user_data: ''
      - name: win-inst-ansible
        instance_type: t3.micro
        image_id: ami-05b85154f69f6bcb3
        count: 1
        os: windows
        user_data: |
          <powershell>
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
          $scriptUrl = "https://raw.githubusercontent.com/ansible/ansible-documentation/ae8772176a5c645655c91328e93196bcf741732d/examples/scripts/ConfigureRemotingForAnsible.ps1"
          Invoke-Expression (Invoke-WebRequest -Uri $scriptUrl -UseBasicParsing).Content
          </powershell>

  tasks:
    - name: Launch EC2 instances
      amazon.aws.ec2_instance:
        name: "{{ item.name }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        instance_type: "{{ item.instance_type }}"
        image_id: "{{ item.image_id }}"
        wait: true
        count: "{{ item.count }}"
        security_group: "{{ security_group }}"
        user_data: "{{ item.user_data }}"
        tags:
          creator: ansible
          os: "{{ item.os }}"
      loop: "{{ ec2_instances }}"
      register: ec2

      # - name: List Public IPv4 Addesses of Instances
      # ansible.builtin.debug:
      #  msg: "{{ item.platform : item.instance_id : item.public_ip_address }}"
      # loop: "{{ ec2_ip.results | map(attribute='instances') | flatten }}"
...
